# Generated by Django 3.2.7 on 2021-10-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=333, unique=True)),
                ('description', models.TextField()),
                ('cart_image', models.ImageField(blank=True, upload_to='categories/photos')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'catergories',
            },
        ),
    ]
