# Generated by Django 3.2.7 on 2021-09-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'catergories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='cart_image',
            field=models.ImageField(blank=True, upload_to='categories/photos'),
        ),
    ]
